# Azure Web App Configuration
# This file configures how Azure Web App runs your Next.js application

# Node.js runtime configuration
runtime: node
runtimeVersion: 20.x

# Startup command - this tells Azure how to start your app
startupCommand: "npm start"

# Environment variables
environmentVariables:
  NODE_ENV: production
  PORT: 8080

# Build configuration
buildConfiguration:
  buildCommand: "npm run build"
  outputDirectory: ".next"
