name: Debug Build Step Execution

on:
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Step 1 - Install Dependencies
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== STEP 1: Installing dependencies ==="
          npm ci
          echo "=== STEP 1 COMPLETED ==="
          
      - name: Step 2 - Debug Current State
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== STEP 2: Debug current state ==="
          echo "Current directory: %CD%"
          dir
          echo "=== STEP 2 COMPLETED ==="
          
      - name: Step 3 - Build Next.js
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== STEP 3: Building Next.js ==="
          echo "Current directory: %CD%"
          echo "Available scripts:"
          npm run
          echo "Running build command..."
          npm run build
          echo "Build exit code: %ERRORLEVEL%"
          echo "=== STEP 3 COMPLETED ==="
          
      - name: Step 4 - Verify Build Output
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== STEP 4: Verifying build output ==="
          echo "Current directory: %CD%"
          echo "Directory contents:"
          dir
          if exist .next (
            echo "✓ .next directory found"
            dir .next
          ) else (
            echo "✗ .next directory missing"
          )
          echo "=== STEP 4 COMPLETED ==="
          
      - name: Step 5 - Final Check
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== STEP 5: Final check ==="
          echo "All steps completed successfully!"
          echo "=== STEP 5 COMPLETED ==="
