name: Frontend Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
    - 'frontend/**'
    - '.github/workflows/frontend-deploy.yml'
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          echo "=== Installing dependencies ==="
          npm ci
          echo "=== Dependencies installed ==="
          
      - name: Build Next.js
        working-directory: ./frontend
        run: |
          echo "=== Building Next.js ==="
          npm run build
          echo "=== Build completed ==="
          
      - name: Verify Build Output
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Verifying build output ==="
          if exist .next (
            echo "✓ .next directory created successfully!"
            dir .next
          ) else (
            echo "✗ .next directory missing"
            echo "Current directory contents:"
            dir
          )
          
      - name: Install Production Dependencies
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Installing production dependencies ==="
          echo "Current directory: %CD%"
          echo "Installing only production dependencies..."
          npm ci --omit=dev --no-audit --no-fund
          echo "✓ Production dependencies installed"
          
      - name: Prepare for Deployment
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Preparing for deployment ==="
          echo "=== BEFORE cleanup - Current directory contents: ==="
          dir
          echo "=== BEFORE cleanup - .next directory verification: ==="
          if exist .next (
            echo "✓ .next directory found before cleanup"
            dir .next
          ) else (
            echo "✗ .next directory missing before cleanup!"
            exit /b 1
          )
          
          echo "=== BEFORE cleanup - node_modules verification: ==="
          if exist node_modules (
            echo "✓ node_modules directory found before cleanup"
            dir node_modules
          ) else (
            echo "✗ node_modules directory missing before cleanup!"
            exit /b 1
          )
          
          echo "=== Removing development files (preserving .next and node_modules) ==="
          if exist .git rmdir /s /q .git
          
          echo "=== AFTER cleanup - Verifying essential directories still exist: ==="
          if exist .next (
            echo "✓ .next directory preserved during cleanup"
            dir .next
          ) else (
            echo "ERROR: .next directory was removed during cleanup!"
            exit /b 1
          )
          
          if exist node_modules (
            echo "✓ node_modules directory preserved during cleanup"
            dir node_modules
          ) else (
            echo "ERROR: node_modules directory was removed during cleanup!"
            exit /b 1
          )
          
          echo "=== FINAL verification - Deployment package ready: ==="
          dir
          echo "=== Essential files check: ==="
          if exist package.json echo "✓ package.json"
          if exist startup.cjs echo "✓ startup.cjs"
          if exist server.cjs echo "✓ server.cjs"
          if exist web.config echo "✓ web.config"
          if exist .deployment echo "✓ .deployment"
          if exist .next echo "✓ .next directory"
          if exist node_modules echo "✓ node_modules directory"
          
      - name: Create Deployment Package
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Creating deployment package ==="
          echo "Current directory: %CD%"
          echo "Creating optimized zip archive..."
          echo "Including essential files: .next, package.json, package-lock.json, startup.cjs, server.cjs, web.config, .deployment, app, components, config, contexts, public, node_modules"
          echo "Note: node_modules included for Azure runtime (production dependencies only)"
          
          powershell -Command "Compress-Archive -Path .next,package.json,package-lock.json,startup.cjs,server.cjs,web.config,.deployment,app,components,config,contexts,public,node_modules -DestinationPath ../deployment-package.zip -Force"
          
          echo "=== Deployment package created ==="
          dir ..\deployment-package.zip
          echo "=== Package size: ==="
          powershell -Command "Get-ChildItem ../deployment-package.zip | Select-Object Name, @{Name='Size(MB)';Expression={[math]::Round($_.Length/1MB,2)}}"
          
      - name: Upload Deployment Package
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: ./deployment-package.zip
          
      - name: Verify Artifact Before Upload
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== VERIFYING ARTIFACT BEFORE UPLOAD ==="
          echo "Current directory: %CD%"
          echo "Directory contents:"
          dir
          echo "=== .next directory verification: ==="
          if exist .next (
            echo "✓ .next directory exists before upload"
            dir .next
            echo "=== .next directory size: ==="
            dir .next /s | findstr "File(s)"
          ) else (
            echo "✗ .next directory missing before upload!"
            exit /b 1
          )
          echo "=== ARTIFACT VERIFICATION COMPLETE ==="
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          
      - name: Extract Deployment Package
        run: |
          echo "=== Extracting deployment package ==="
          echo "Current directory: $(pwd)"
          echo "Downloaded files:"
          ls -la
          echo "=== Verifying zip contents ==="
          unzip -l deployment-package.zip | head -30
          echo "=== Extracting deployment-package.zip... ==="
          unzip -q deployment-package.zip || true
          echo "=== Extraction completed ==="
          echo "Extracted contents:"
          ls -la
          
      - name: Verify Artifact After Download
        run: |
          echo "=== VERIFYING ARTIFACT AFTER DOWNLOAD ==="
          echo "Current directory: $(pwd)"
          echo "Root directory contents:"
          ls -la
          echo "=== .next directory verification: ==="
          if [ -d ".next" ]; then
            echo "✓ .next directory exists after download"
            ls -la .next
            echo "=== .next directory size: ==="
            du -sh .next/ 2>/dev/null || echo "Size calculation had permission issues (non-critical)"
            echo "=== .next directory file count: ==="
            find .next -type f 2>/dev/null | wc -l || echo "File count had permission issues (non-critical)"
            echo "✓ .next directory verification successful"
          else
            echo "✗ .next directory missing after download!"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi
          echo "=== ARTIFACT DOWNLOAD VERIFICATION COMPLETE ==="
          
      - name: Verify Deployment Package
        run: |
          echo "=== Verifying deployment package ==="
          echo "Current directory: $(pwd)"
          echo "Current directory contents:"
          ls -la
          echo "=== Package.json contents: ==="
          cat package.json
          echo "=== Package-lock.json verification ==="
          if [ -f "package-lock.json" ]; then
            echo "✓ package-lock.json found (required for npm ci)"
            ls -la package-lock.json
          else
            echo "✗ package-lock.json missing!"
          fi
          echo "=== Essential files check ==="
          if [ -d ".next" ]; then echo "✓ .next directory"; fi
          if [ -f "startup.cjs" ]; then echo "✓ startup.cjs"; fi
          if [ -f "server.cjs" ]; then echo "✓ server.cjs"; fi
          if [ -f "web.config" ]; then echo "✓ web.config"; fi
          if [ -f ".deployment" ]; then echo "✓ .deployment"; fi
          if [ -d "node_modules" ]; then echo "✓ node_modules directory"; fi
          echo "Final directory contents:"
          ls -la
          
      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TaskFlow'
          slot-name: 'Production'
          package: deployment-package.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
