name: Azure Functions Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - "functions/**"
      - ".github/workflows/functions-deploy.yml"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        working-directory: ./functions
        run: dotnet restore

      - name: Build
        working-directory: ./functions
        run: dotnet build --no-restore --configuration Release

      - name: Publish
        working-directory: ./functions
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Create Deployment Package
        working-directory: ./functions
        shell: cmd
        run: |
          echo "=== Creating functions deployment package ==="
          echo "Current directory: %CD%"
          echo "Creating zip archive..."

          powershell -Command "Compress-Archive -Path ./publish/* -DestinationPath ./output.zip -Force"

          echo "=== Functions deployment package created ==="
          dir output.zip

      - name: Upload Functions Deployment Package
        uses: actions/upload-artifact@v4
        with:
          name: functions-build
          path: ${{ github.workspace }}/functions/output.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AZURE_FUNCTIONAPP_NAME: 'UserRegistrationFunction'
      AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions'

    steps:
      - name: Download Functions Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: functions-build

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
