# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TaskFlow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Installing dependencies ==="
          npm ci
          echo "=== Dependencies installed successfully ==="

      - name: Build Next.js application
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Starting Next.js build ==="
          npm run build
          echo "=== Build completed, exit code: %ERRORLEVEL% ==="
          
          if %ERRORLEVEL% neq 0 (
            echo "ERROR: Build failed with exit code %ERRORLEVEL%"
            exit /b 1
          )
          
          echo "=== Verifying build output ==="
          if not exist .next (
            echo "ERROR: .next directory not found after build"
            dir
            exit /b 1
          )
          
          echo "=== Build successful! .next directory contents: ==="
          dir .next
          echo "=== .next/static contents: ==="
          if exist .next\static dir .next\static
          echo "=== .next/server contents: ==="
          if exist .next\server dir .next\server

      - name: Clean up for deployment
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Cleaning up for deployment ==="
          echo "=== Preserving essential files: .next, package.json, server.cjs, web.config, .deployment ==="
          
          # Remove development files but keep build output and Azure config
          if exist .git rmdir /s /q .git
          if exist *.log del /q *.log
          if exist .env.local del /q .env.local
          if exist .env.development.local del /q .env.development.local
          if exist .env.test.local del /q .env.test.local
          if exist .env.production.local del /q .env.production.local
          if exist tsconfig.tsbuildinfo del /q tsconfig.tsbuildinfo
          if exist node_modules rmdir /s /q node_modules
          
          echo "=== Final package contents: ==="
          dir
          echo "=== Verifying .next still exists: ==="
          if exist .next (
            echo "SUCCESS: .next directory preserved"
            dir .next
          ) else (
            echo "ERROR: .next directory was removed during cleanup!"
            exit /b 1
          )
          echo "=== Verifying Azure config files: ==="
          if exist .deployment (
            echo "SUCCESS: .deployment file preserved"
          ) else (
            echo "ERROR: .deployment file was removed!"
            exit /b 1
          )
          
          echo "=== Installing production dependencies ==="
          npm ci --only=production
          echo "=== Installing PM2 globally ==="
          npm install -g pm2
          echo "=== Production dependencies installed ==="
          
          echo "=== Setting up startup script ==="
          echo "=== Making startup.js executable ==="
          echo "=== Verifying startup.js exists: ==="
          if exist startup.js (
            echo "SUCCESS: startup.js found"
            type startup.js
          ) else (
            echo "ERROR: startup.js not found!"
            exit /b 1
          )
          
          echo "=== Final deployment package structure: ==="
          echo "=== Root directory: ==="
          dir
          echo "=== Essential files check: ==="
          if exist package.json echo "✓ package.json"
          if exist startup.js echo "✓ startup.js"
          if exist server.cjs echo "✓ server.cjs"
          if exist web.config echo "✓ web.config"
          if exist .deployment echo "✓ .deployment"
          if exist azure-webapp.config.js echo "✓ azure-webapp.config.js"
          if exist .next echo "✓ .next directory"
          echo "=== .next directory contents: ==="
          dir .next
          echo "=== Package.json contents: ==="
          type package.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TaskFlow'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_352C29692F204B188AA07AED5952DEFE }}
          
      - name: 'Verify deployment structure'
        run: |
          echo "=== Verifying deployed files ==="
          echo "=== Root directory contents: ==="
          ls -la
          echo "=== Essential files check: ==="
          [ -f "package.json" ] && echo "✓ package.json" || echo "✗ package.json missing"
          [ -f "startup.js" ] && echo "✓ startup.js" || echo "✗ startup.js missing"
          [ -f "server.cjs" ] && echo "✓ server.cjs" || echo "✗ server.cjs missing"
          [ -f "web.config" ] && echo "✓ web.config" || echo "✗ web.config missing"
          [ -f ".deployment" ] && echo "✓ .deployment" || echo "✗ .deployment missing"
          [ -f "azure-webapp.config.js" ] && echo "✓ azure-webapp.config.js" || echo "✗ azure-webapp.config.js missing"
          [ -d ".next" ] && echo "✓ .next directory" || echo "✗ .next directory missing"
          echo "=== .next directory contents: ==="
          if [ -d ".next" ]; then
            ls -la .next
            echo "=== .next/static contents: ==="
            ls -la .next/static || echo "No static directory"
            echo "=== .next/server contents: ==="
            ls -la .next/server || echo "No server directory"
          else
            echo "ERROR: .next directory not found in deployment!"
            exit 1
          fi
          echo "=== Package.json: ==="
          cat package.json
      
      - name: 'Kudu Deployment (Alternative)'
        if: failure()
        run: |
          echo "OneDeploy failed, trying Kudu deployment..."
          echo "Manual deployment required via Kudu or Azure Portal"
          echo "Go to: https://taskflow-c8fyfpdcbwgefwg9.scm.canadacentral-01.azurewebsites.net/"
          echo "Use Debug Console to upload files manually"
