# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TaskFlow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        working-directory: ./frontend
        run: |
          npm install
          npm run build
          npm run test --if-present
      
      - name: Prepare deployment package
        working-directory: ./frontend
        run: |
          # Create a clean deployment directory
          mkdir ..\deploy
          # Copy only the files needed for production
          xcopy .next ..\deploy\.next /E /I /Y
          xcopy public ..\deploy\public /E /I /Y
          copy package.json ..\deploy\
          copy package-lock.json ..\deploy\
          copy next.config.ts ..\deploy\
          copy tailwind.config.js ..\deploy\
          copy tsconfig.json ..\deploy\
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ..\deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Install production dependencies
        run: |
          npm ci --omit=dev
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TaskFlow'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3096CF908AD24070BB116DE0496C5F86 }}