# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TaskFlow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Installing dependencies ==="
          npm ci
          echo "=== Dependencies installed successfully ==="

      - name: Build Next.js application
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Starting Next.js build ==="
          npm run build
          echo "=== Build completed, exit code: %ERRORLEVEL% ==="
          
          if %ERRORLEVEL% neq 0 (
            echo "ERROR: Build failed with exit code %ERRORLEVEL%"
            exit /b 1
          )
          
          echo "=== Verifying build output ==="
          if not exist .next (
            echo "ERROR: .next directory not found after build"
            dir
            exit /b 1
          )
          
          echo "=== Build successful! .next directory contents: ==="
          dir .next
          echo "=== .next/static contents: ==="
          if exist .next\static dir .next\static
          echo "=== .next/server contents: ==="
          if exist .next\server dir .next\server

      - name: Clean up for deployment
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Cleaning up for deployment ==="
          echo "=== Preserving essential files: .next, package.json, server.cjs, web.config ==="
          
          # Remove development files but keep build output
          if exist .git rmdir /s /q .git
          if exist *.log del /q *.log
          if exist .env.local del /q .env.local
          if exist .env.development.local del /q .env.development.local
          if exist .env.test.local del /q .env.test.local
          if exist .env.production.local del /q .env.production.local
          if exist tsconfig.tsbuildinfo del /q tsconfig.tsbuildinfo
          
          echo "=== Final package contents: ==="
          dir
          echo "=== Verifying .next still exists: ==="
          if exist .next (
            echo "SUCCESS: .next directory preserved"
            dir .next
          ) else (
            echo "ERROR: .next directory was removed during cleanup!"
            exit /b 1
          )

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TaskFlow'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_352C29692F204B188AA07AED5952DEFE }}
      
      - name: 'Kudu Deployment (Alternative)'
        if: failure()
        run: |
          echo "OneDeploy failed, trying Kudu deployment..."
          echo "Manual deployment required via Kudu or Azure Portal"
          echo "Go to: https://taskflow-c8fyfpdcbwgefwg9.scm.canadacentral-01.azurewebsites.net/"
          echo "Use Debug Console to upload files manually"
