name: Working Build Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          echo "=== Installing dependencies ==="
          npm ci
          echo "=== Dependencies installed ==="
          
      - name: Build Next.js
        working-directory: ./frontend
        run: |
          echo "=== Building Next.js ==="
          npm run build
          echo "=== Build completed ==="
          
      - name: Verify Build Output
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Verifying build output ==="
          if exist .next (
            echo "✓ .next directory created successfully!"
            dir .next
          ) else (
            echo "✗ .next directory missing"
            echo "Current directory contents:"
            dir
          )
          
      - name: Prepare for Deployment
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== Preparing for deployment ==="
          echo "=== BEFORE cleanup - Current directory contents: ==="
          dir
          echo "=== BEFORE cleanup - .next directory verification: ==="
          if exist .next (
            echo "✓ .next directory found before cleanup"
            dir .next
          ) else (
            echo "✗ .next directory missing before cleanup!"
            exit /b 1
          )
          
          echo "=== Removing development files (preserving .next) ==="
          if exist node_modules rmdir /s /q node_modules
          if exist .git rmdir /s /q .git
          
          echo "=== AFTER cleanup - Verifying .next still exists: ==="
          if exist .next (
            echo "✓ .next directory preserved during cleanup"
            dir .next
          ) else (
            echo "ERROR: .next directory was removed during cleanup!"
            exit /b 1
          )
          
          echo "=== Installing production dependencies ==="
          npm ci --only=production
          echo "=== Production dependencies installed ==="
          
          echo "=== FINAL verification - Deployment package ready: ==="
          dir
          echo "=== Essential files check: ==="
          if exist package.json echo "✓ package.json"
          if exist startup.js echo "✓ startup.js"
          if exist server.cjs echo "✓ server.cjs"
          if exist web.config echo "✓ web.config"
          if exist .deployment echo "✓ .deployment"
          if exist .next echo "✓ .next directory"
          if exist node_modules echo "✓ node_modules (production)"
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: ./frontend
          
      - name: Verify Artifact Before Upload
        working-directory: ./frontend
        shell: cmd
        run: |
          echo "=== VERIFYING ARTIFACT BEFORE UPLOAD ==="
          echo "Current directory: %CD%"
          echo "Directory contents:"
          dir
          echo "=== .next directory verification: ==="
          if exist .next (
            echo "✓ .next directory exists before upload"
            dir .next
            echo "=== .next directory size: ==="
            dir .next /s | findstr "File(s)"
          ) else (
            echo "✗ .next directory missing before upload!"
            exit /b 1
          )
          echo "=== ARTIFACT VERIFICATION COMPLETE ==="
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TaskFlow'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_352C29692F204B188AA07AED5952DEFE }}
